import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Footer from "@/components/ui/Footer";
import NavBar from "@/components/ui/NavBar";
import BGLeft from "@/components/ui/BGLeft";
import BGRight from "@/components/ui/BGRight";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-950 text-zinc-50`}
      >
        <Provider>
          <NavBar />
          <div className="fixed inset-0 -z-20 ">
            <BGRight />
            <BGLeft/> 
          </div>
          {children}
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  );
}
